# Generated by Django 5.2.7 on 2025-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
