# Generated by Django 5.2.7 on 2025-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_appointment_token_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
