# Generated by Django 5.2.7 on 2025-11-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_rename_patient_appointment_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.IntegerField(default=1000),
        ),
    ]
