# Generated by Django 5.2.7 on 2025-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(blank=True, help_text='List all medicines with dosage', null=True),
        ),
    ]
