# Generated by Django 5.2.7 on 2025-11-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_alter_prescription_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
