# Generated by Django 5.2.7 on 2025-11-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_callbackrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
