# Generated by Django 5.2.7 on 2025-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_alter_callbackrequest_preferred_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='preferred_time',
            field=models.CharField(blank=True, default='Morning', max_length=50),
            preserve_default=False,
        ),
    ]
